stages:
  ingest:
    cmd: python src/ingest_xm.py
    deps:
      - src/ingest_xm.py
    outs:
      - data/raw/price_xm_daily.csv:
          cache: true
  
  train:
    cmd: python -m src.train
    deps:
      - src/train.py
      - data/raw/price_xm_daily.csv
    outs:
      - models/lgbm_model.txt:
          cache: true
  
  predict:
    cmd: python -m src.predict
    deps:
      - src/predict.py
      - models/lgbm_model.txt
      - data/raw/price_xm_daily.csv
    outs:
      - data/processed/prediction.csv:
          cache: false