stages:
  ingest:
    cmd: python src/ingest_xm.py
    deps:
      - src/ingest_xm.py
    outs:
      - data/raw/price_xm_daily.csv:
          cache: true
      - data/raw/price_xm_hourly.csv:
          cache: true

  train:
    cmd: python -m src.train
    deps:
      - src/train.py
      - src/features.py
      - data/raw/price_xm_daily.csv
    params:
      - train
    outs:
      - models/candidate/lgbm_model.txt:
          cache: true
    metrics:
      - metrics/candidate.json:
          cache: false
